#! /bin/bash

make -C ..

echo -e "\e[34m----------------------------------------------------------\033[0m"

echo -e "\e[33mtest_part1_count:\033[0m"

./test_part1_count

echo
echo -e "\e[34m----------------------------------------------------------\033[0m"

echo -e "\e[33mtest_part1_order:\033[0m"

./test_part1_order

echo
echo -e "\e[34m----------------------------------------------------------\033[0m"

echo -e "\e[33mtest_part2_count:\033[0m"

./test_part2_count

echo
echo -e "\e[34m----------------------------------------------------------\033[0m"

echo -e "\e[33mtest_part2_order:\033[0m"

./test_part2_order

