#!/bin/bash
if [[ $# != 0 ]]; then
  echo "Usage: findclass"
  exit 1
fi
echo "Welcome to Class Finder!"
echo -n "Please enter part or all of a class name to search for:"
read CLASS
NUMFOUND=0
NUMFOUND=$(cut -d',' -f1 classes | grep "$CLASS" | sort | uniq | wc -l)
if [ $NUMFOUND -eq 0 ]; then
  echo "Sorry, I could not find that class."
  exit 1
fi

if [ $NUMFOUND -gt 1 ]; then
  echo "I found $NUMFOUND matches!"
  echo "You might want to be more specific."
  echo "The first of these matches is:"
fi

CLASSNAME=$(cut -d',' -f1 classes | grep "$CLASS" | sort | head -n 1)
TITLE=$(grep "$CLASSNAME" classes | head -n 1 | cut -d',' -f4)
PROFESSOR=$(grep "$CLASSNAME" classes | head -n 1 | cut -d',' -f11)
LECTURES=$(grep "$CLASSNAME" classes | cut -d',' -f3 | grep "Lecture" | grep -v '^[[:space:]]*$' | wc -l)
LABS=$(grep "$CLASSNAME" classes | cut -d',' -f3 | grep "Laboratory" | grep -v '^[[:space:]]*$' | wc -l)
PSOS=$(grep "$CLASSNAME" classes | cut -d',' -f3 | grep "Pso" | grep -v '^[[:space:]]*$' | wc -l)
OTHERS=$(grep "$CLASSNAME" classes | cut -d',' -f3 | grep -v "Lecture" | grep -v "Laboratory" | grep -v "Pso" | grep -v '^[[:space:]]*$' | wc -l)

echo "Name: $CLASSNAME"
echo "Title: $TITLE"
echo "Professor: $PROFESSOR"
echo "Lectures: $LECTURES"
echo "Labs: $LABS"
echo "PSOs: $PSOS"
echo "Others: $OTHERS"

exit 0
