#!/bin/bash
#important variables
WIDTH=$1
LOWER_LIMIT=$2
UPPER_LIMIT=$3
VAR_A=$4
VAR_B=$5
VAR_C=$6
VAR_X=LOWER_LIMIT
LENGTH=UPPER_LIMIT-LOWER_LIMIT
SUM=0
if [ $# != 6 ]; then
  echo "Usage: riemann <delta x> <lower limit> <upper limit> <a> <b> <c>"
  exit 1
fi
while ((${LENGTH}>0)); do
  ((SUM=SUM+((VAR_A*VAR_X*VAR_X + VAR_B*VAR_X + VAR_C)*WIDTH)))
  ((VAR_X=VAR_X+WIDTH))
  ((LENGTH=LENGTH-1))
done
echo ${SUM}
exit 0
